### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by HP192080042** [FlyuZ/voxelmorph-tf2-min#1]
您好 我跑出来出现这样的错误  tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]

我安装的是tensorflow2.0版本    望指点！  

@FlyuZ

**Comment by FlyuZ** [comment]
@HP192080042 
您好，如果您使用的是RTX系列显卡，并出现Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR，这样的错误，可以参考这个：https://github.com/tensorflow/tensorflow/issues/24496

**Comment by HP192080042** [comment]
其他我自己的tf模型我是可以运行的&nbsp; &nbsp;但是跑你这个模型出现了错误&nbsp; 他会显示三张图片&nbsp; 然后就会出现这个错误&nbsp; &nbsp; 不知道是怎么回事 望赐教&nbsp; 我用的的GTX1080Ti cuda10.0&nbsp; window系统&nbsp; tf2.0&nbsp; &nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 中午11:24
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042
 您好，如果您使用的是RTX系列显卡，并出现Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR，这样的错误，可以参考这个：tensorflow/tensorflow#24496

**Comment by FlyuZ** [comment]
@HP192080042 尝试在代码最前面添加，看是否能解决  
`
import tensorflow as tf  
config = tf.compat.v1.ConfigProto()  
config.gpu_options.allow_growth = True  
session = tf.compat.v1.Session(config=config)  
`

或：

`
physical_devices = tf.config.experimental.list_physical_devices('GPU')  
tf.config.experimental.set_memory_growth(physical_devices[0], True)  
`

**Comment by HP192080042** [comment]
我在 tf2.vm.py中添加了&nbsp; 还是同样的问题&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 中午11:40
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 尝试在代码最前面添加，看是否能解决
 `
 import tensorflow as tf
 
config = tf.compat.v1.ConfigProto()
 config.gpu_options.allow_growth = True
 session = tf.compat.v1.Session(config=config)
 或：
 physical_devices = tf.config.experimental.list_physical_devices('GPU')
 tf.config.experimental.set_memory_growth(physical_devices[0], True)
 `

**Comment by FlyuZ** [comment]
@HP192080042 我找了一台没有配环境的电脑，gtx1060，装上tf2-gpu,cuda10.0,cudnn7.6.4，下载代码并修改路径后，可以运行成功。

**Comment by HP192080042** [comment]
能够发一下你最后运行的结果是啥吗？&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 中午1:06
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 我找了一台没有配环境的电脑，gtx1060，装上tf2-gpu,cuda10.0,cudnn7.6.4，下载代码并修改路径后，可以运行成功。

**Comment by HP192080042** [comment]
我的cudnn版本是7.5.0 是不是cudnn版本的问题？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 中午1:06
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 我找了一台没有配环境的电脑，gtx1060，装上tf2-gpu,cuda10.0,cudnn7.6.4，下载代码并修改路径后，可以运行成功。

**Comment by HP192080042** [comment]
您好&nbsp; 我将cudnn7.5 换为7.6 之前那个问题解决了 不过出现了一个新的错误&nbsp;Failed to convert a NumPy array to a Tensor (Unsupported numpy type: NPY_INT) 望指教 谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 中午1:06
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 我找了一台没有配环境的电脑，gtx1060，装上tf2-gpu,cuda10.0,cudnn7.6.4，下载代码并修改路径后，可以运行成功。

**Comment by FlyuZ** [comment]
@HP192080042 我猜测可能是tensorflow安装的有问题，2.0中内置keras。

**Comment by HP192080042** [comment]
你有没有好的tensorflow2的安装链接 我重新安装一下&nbsp; cuda应该不用重新安装了 谢谢啦






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 下午2:56
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 我猜测可能是tensorflow安装的有问题，2.0中内置keras。

**Comment by FlyuZ** [comment]
@HP192080042 请私信我您的联系方式

**Comment by HP192080042** [comment]
微信&nbsp; 19975267486&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 下午3:03
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 请私信我您的联系方式

**Comment by HP192080042** [comment]
微信 19975267486&nbsp; &nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Feifei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月23日(星期六) 下午3:03
收件人:&nbsp;"FlyuZ/voxelmorph-tf2-min"<voxelmorph-tf2-min@noreply.github.com&gt;;
抄送:&nbsp;"上善若水"<793161814@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlyuZ/voxelmorph-tf2-min] wrong (#1)




@HP192080042 请私信我您的联系方式
